FROM golang:1.26.2-alpine

WORKDIR /app

# Install make, air, oapi-codegen
RUN apk add --no-cache make
RUN go install github.com/air-verse/air@latest
RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]